name: Build and deploy to github pages
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npm run build
      - name: 'Run peaceiris/actions-gh-pages@v3: deploy to github pages'
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          publish_dir: ./build
          cname: eliko.ga
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
